### ISSUE TITLE
Call to undefined function socket_create()

### ISSUE THREAD

**Issue by brsnik** [svnindia/smpp-client-php#2]
Just tried to run your script and get the error below:

`Fatal error: Uncaught Error: Call to undefined function socket_create() in /php-smpp-master/sockettransport.class.php:218 Stack trace: #0 /php-smpp-master/receive.php(18): SocketTransport->open() #1 {main} thrown in /php-smpp-master/sockettransport.class.php on line 218`

My PHP Sockets are open...so what could be causing this error?

**Comment by brsnik** [comment]
Managed to work the socket problem.

But get this now:

`Fatal error: Uncaught SmppException: Error in the optional part of the PDU Body. in /php-smpp-master/smppclient.class.php:622 Stack trace: #0 /php-smpp-master/smppclient.class.php(392): SmppClient->sendCommand(4, '\x00\x05\x00SMPP Test\x00\x01\x01...') #1 /php-smpp-master/smppclient.class.php(340): SmppClient->submit_sm(Object(SmppAddress), Object(SmppAddress), 'H\eello world', NULL, 0) #2 /php-smpp-master/send.php(33): SmppClient->sendSMS(Object(SmppAddress), Object(SmppAddress), 'H\eello world', NULL) #3 {main} thrown in /php-smpp-master/smppclient.class.php on line 622`
